CREATE TABLE Gender (
	Id		INT PRIMARY KEY IDENTITY(1,1),
	Name	VARCHAR(20) NOT NULL
);

CREATE TABLE Person (
	Id			INT PRIMARY KEY IDENTITY(1,1),
	Name		VARCHAR(100) NOT NULL,
	Email		VARCHAR(50) NOT NULL,
	GenderId	INT FOREIGN KEY	REFERENCES dbo.Gender(Id) NOT NULL
);